import re
from datetime import datetime, timedelta
from ics import Calendar, Event
import arrow

def predefined(date_from_llm, time_str, event_name):
    date_clean = date_from_llm.strip()
    date_iso = date_clean

    formats = [
        "%d/%m/%Y",
        "%d-%m-%Y",
        "%d/%m/%y",
        "%d-%m-%y",
        "%d.%m.%Y",
        "%Y-%m-%d",
        "%d-%b-%Y"
    ]

    for fmt in formats:
        try:
            date_obj = datetime.strptime(date_clean, fmt)
            date_iso = date_obj.strftime("%Y-%m-%d")
            break
        except ValueError:
            continue

    event_lower = normalize_event_name(event_name).lower()
    time_clean = time_str.strip().upper()

    is_compre = (
        "comprehensive" in event_lower or
        "compre" in event_lower or
        "final exam" in event_lower
    )

    if is_compre:
        if "FN" in time_clean:
            return f"{date_iso}T10:00:00", f"{date_iso}T13:00:00"
        elif "AN" in time_clean:
            return f"{date_iso}T14:00:00", f"{date_iso}T17:00:00"

    times = list(re.finditer(r"(\d{1,2})(?::(\d{2}))?", time_clean))

    if ("MIN" in time_clean or "HRS" in time_clean) and not (":" in time_clean or "AM" in time_clean or "PM" in time_clean):
        return "Time not found", date_iso
      
    if not times:
        return "Time not found", date_iso
    
    start_dt = None
    end_dt = None

    is_pm = "PM" in time_clean
    is_am = "AM" in time_clean

    t1 = times[0]
    hour1 = int(t1.group(1))
    minute1 = int(t1.group(2) or 0)

    try:        
        if len(times) > 1:
            t2 = times[1]
            hour2 = int(t2.group(1))
            minute2 = int(t2.group(2) or 0)

            only_pm = is_pm and not is_am

            if not is_pm and not is_am and hour2 < hour1:
                only_pm = True

            hour2_24 = to_24h(hour2, only_pm)
            end_candid = datetime.strptime(f"{date_iso} {hour2_24:02d}:{minute2:02d}:00", "%Y-%m-%d %H:%M:%S")

            hour1_am = to_24h(hour1, False)
            candid_am = datetime.strptime(f"{date_iso} {hour1_am:02d}:{minute1:02d}:00", "%Y-%m-%d %H:%M:%S")

            h1_pm = to_24h(hour1, True)
            candid_pm = datetime.strptime(f"{date_iso} {h1_pm:02d}:{minute1:02d}:00", "%Y-%m-%d %H:%M:%S")

            difference_am = (end_candid - candid_am).total_seconds() / 3600
            difference_pm = (end_candid - candid_pm).total_seconds() / 3600

            if 0.5 <= difference_pm <= 6:
                start_dt = candid_pm
            elif 0.5 <= difference_am <= 6:
                start_dt = candid_am
            else:
                start_dt = candid_am

            if end_candid < start_dt:
                end_candid += timedelta(hours=12)
            
            end_dt = end_candid

        else:
            is_pm_start = is_pm

            if not is_pm and not is_am:
                if 1 <= hour1 <= 6:
                    is_pm_start = True
            
            hour1_final = to_24h(hour1, is_pm_start)

            start_dt = datetime.strptime(f"{date_iso} {hour1_final:02d}:{minute1:02d}:00", "%Y-%m-%d %H:%M:%S")
            end_dt = start_dt + timedelta(hours=1, minutes=30)

        return start_dt.isoformat(), end_dt.isoformat()
    
    except ValueError:
        pass
        
    return "Time not found", date_iso

def clean_subject_key(sub_name):
    if not sub_name: return ""
    return sub_name.lower().split('(')[0].strip()

def normalize_event_name(event_name):
    name = event_name.lower().strip()

    if any(x in name for x in ['compre', 'final exam', 'end sem', 'finals']):
        return "Comprehensive Exam"
    if any(x in name for x in ["midsem", "mid-sem", "mid sem"]):
        return "MidSem Exam"

    return event_name.title()

# THANK YOU GEMINI FOR TO_24H FUNCTION CODE AND IDEA TO USE THIS
def to_24h(h, is_pm):
        if is_pm:
            if h < 12: return h + 12
            if h == 12: return 12
            return h
        else:
            if h == 12: return 0 # 12 AM
            return h

def save_ics(events, filename):
    c = Calendar()

    for item in events:
        e = Event()
        e.name = item['Subject']

        if "TIME TBA" in item['Subject']:
            date_only = item['Start_DateTime'].split("T")[0]
            e.begin = arrow.get(date_only)
            e.make_all_day()
        else:
            e.begin = arrow.get(item['Start_DateTime']).replace(tzinfo='Asia/Kolkata')
            e.end = arrow.get(item['End_DateTime']).replace(tzinfo='Asia/Kolkata')

        description = (
            f"Event Name: {item['Event_Name']}\n"
            f"Format: {item['Format']}\n"
            f"Weightage: {item['Weightage']}\n"
            f"Raw Time String: {item['Raw_Time_String']}\n"
            f"++++++++++++++++++++++++++\n"
            f"Generated by AI Agent"
        )

        e.description = description

        c.events.add(e)

    with open(filename, 'w', encoding="utf-8") as f:
        f.writelines(c.serialize())
    
    print(f"ICS file saved as {filename}")

